INSERT INTO USER(user_id, user_nickname, user_name, password) VALUES(1, 'jaein', '재인', 'aaa');


INSERT INTO INTEREST_JOB(EDUCATION, AVERAGE_SALARY, CAREER, JOB, JOB_NUMBER, PREFERENTIAL_TREATMENT, REGION, SALARY, SECTORS, STATISTICS, TITLE, WELFARE, WORK_TYPE, DEADLINE, COMPANY_NAME, USER_ID) VALUES('학력 무관', '2800', '경력 무관', '운송·운수·물류','42320380', '해당 분야 전공자 및 유경험자 우대', '경기도 성남시', '2600', 'IT웹 서비스', 80, '이자경수학 아이파크관에서 고등 수학선생님 구인합니다', '4대 보험', '정규직', '상시채용', '아이엘그룹', 1);
INSERT INTO INTEREST_JOB(EDUCATION, AVERAGE_SALARY, CAREER, JOB, JOB_NUMBER, PREFERENTIAL_TREATMENT, REGION, SALARY, SECTORS, STATISTICS, TITLE, WELFARE, WORK_TYPE, DEADLINE, COMPANY_NAME, USER_ID) VALUES('학사 이상', '3200', '경력 1년이상', '화물운송 중개, 대리 및 관련 서비스업','42377191', '해당 분야 전공자 및 유경험자 우대', '경기도 안산시', '3400', 'IT웹 서비스', 10, '[용인] (주)삼덕티엘에스 행정지원 직무 채용', '4대 보험', '정규직','3월말', '삼덕티엘에스', 1);
INSERT INTO INTEREST_JOB(EDUCATION, AVERAGE_SALARY, CAREER, JOB, JOB_NUMBER, PREFERENTIAL_TREATMENT, REGION, SALARY, SECTORS, STATISTICS, TITLE, WELFARE, WORK_TYPE, DEADLINE, COMPANY_NAME, USER_ID) VALUES('석사 이상', '3000', '경력 3년이상', '기타 화학물질 및 화학제품 도매업','42349073', '해당 분야 전공자 및 유경험자 우대', '경기도 용인시', '3800', 'IT웹 서비스', 180, '[업계1위 자동차 관련 방청부품] 영업지원 사무직 채용', '4대 보험', '정규직','3/18', '(주)뉴텍상사', 1);
INSERT INTO INTEREST_JOB(EDUCATION, AVERAGE_SALARY, CAREER, JOB, JOB_NUMBER, PREFERENTIAL_TREATMENT, REGION, SALARY, SECTORS, STATISTICS, TITLE, WELFARE, WORK_TYPE, DEADLINE, COMPANY_NAME, USER_ID) VALUES('학사 이상', '2600', '경력 무관', '투자 자문업 및 투자 일임업','42358928', '금융 관련 종사자 우대', '인천광역시 부평구', '2800', 'IT웹 서비스', 60, '[서울] 증권영업/아웃바운드/텔레마케터 외 경력무관 채용 공고', '4대 보험', '정규직', '3/12', '(주)에이치비투자그룹', 1);
INSERT INTO INTEREST_JOB(EDUCATION, AVERAGE_SALARY, CAREER, JOB, JOB_NUMBER, PREFERENTIAL_TREATMENT, REGION, SALARY, SECTORS, STATISTICS, TITLE, WELFARE, WORK_TYPE, DEADLINE, COMPANY_NAME, USER_ID) VALUES('학력 무관', '2800', '경력 무관', '기타 수산동물 가공 및 저장 처리업','42370652', '해당 분야 전공자 및 유경험자 우대', '서울특별시 강남구', '2800', 'IT웹 서비스', 20, '㈜코주부씨앤에프, ㈜코주부프레쉬쿡 , ㈜S&K 글로벌 각 부문 채용', '4대 보험', '정규직','상시채용', '(주)코주부씨앤에프', 1);


insert into compare_box(job_Number1, job_Number2, job_Number3, user_id) values(1,1,1,1);